/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedWorkbenchRouteImport } from './routes/_authenticated/workbench'
import { Route as AuthenticatedTenantsRouteImport } from './routes/_authenticated/tenants'
import { Route as AuthenticatedTenanciesRouteImport } from './routes/_authenticated/tenancies'
import { Route as AuthenticatedSuppliersRouteImport } from './routes/_authenticated/suppliers'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedPropertiesRouteImport } from './routes/_authenticated/properties'
import { Route as AuthenticatedOwnersRouteImport } from './routes/_authenticated/owners'
import { Route as AuthenticatedMarketingRouteImport } from './routes/_authenticated/marketing'
import { Route as AuthenticatedMaintenanceRouteImport } from './routes/_authenticated/maintenance'
import { Route as AuthenticatedLeasingProcessRouteImport } from './routes/_authenticated/leasing-process'
import { Route as AuthenticatedInvestorRouteImport } from './routes/_authenticated/investor'
import { Route as AuthenticatedInspectionsRouteImport } from './routes/_authenticated/inspections'
import { Route as AuthenticatedFinancialsRouteImport } from './routes/_authenticated/financials'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedComplianceRouteImport } from './routes/_authenticated/compliance'
import { Route as AuthenticatedAiInsightsRouteImport } from './routes/_authenticated/ai-insights'
import { Route as AuthenticatedAccountingRouteImport } from './routes/_authenticated/accounting'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authOtpRouteImport } from './routes/(auth)/otp'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as AuthenticatedSuppliersIndexRouteImport } from './routes/_authenticated/suppliers/index'
import { Route as AuthenticatedReportsIndexRouteImport } from './routes/_authenticated/reports.index'
import { Route as AuthenticatedPropertiesIndexRouteImport } from './routes/_authenticated/properties.index'
import { Route as AuthenticatedLeasingProcessIndexRouteImport } from './routes/_authenticated/leasing-process/index'
import { Route as AuthenticatedSuppliersReviewsRouteImport } from './routes/_authenticated/suppliers/reviews'
import { Route as AuthenticatedSuppliersQuotesRouteImport } from './routes/_authenticated/suppliers/quotes'
import { Route as AuthenticatedSuppliersAssignmentsRouteImport } from './routes/_authenticated/suppliers/assignments'
import { Route as AuthenticatedReportsRentalPriceRouteImport } from './routes/_authenticated/reports.rental-price'
import { Route as AuthenticatedPropertiesPropertyIdRouteImport } from './routes/_authenticated/properties/$propertyId'
import { Route as AuthenticatedMarketingOldOwnersRouteImport } from './routes/_authenticated/marketing/old-owners'
import { Route as AuthenticatedMarketingLeadsRouteImport } from './routes/_authenticated/marketing/leads'
import { Route as AuthenticatedLeasingProcessViewingRouteImport } from './routes/_authenticated/leasing-process/viewing'
import { Route as AuthenticatedLeasingProcessListingRouteImport } from './routes/_authenticated/leasing-process/listing'
import { Route as AuthenticatedLeasingProcessApplicationsRouteImport } from './routes/_authenticated/leasing-process/applications'
import { Route as AuthenticatedLeasingProcessAgreementsRouteImport } from './routes/_authenticated/leasing-process/agreements'
import { Route as AuthenticatedAccountingAuditRouteImport } from './routes/_authenticated/accounting/audit'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWorkbenchRoute = AuthenticatedWorkbenchRouteImport.update({
  id: '/workbench',
  path: '/workbench',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTenantsRoute = AuthenticatedTenantsRouteImport.update({
  id: '/tenants',
  path: '/tenants',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTenanciesRoute = AuthenticatedTenanciesRouteImport.update({
  id: '/tenancies',
  path: '/tenancies',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSuppliersRoute = AuthenticatedSuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPropertiesRoute = AuthenticatedPropertiesRouteImport.update({
  id: '/properties',
  path: '/properties',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOwnersRoute = AuthenticatedOwnersRouteImport.update({
  id: '/owners',
  path: '/owners',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMarketingRoute = AuthenticatedMarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMaintenanceRoute =
  AuthenticatedMaintenanceRouteImport.update({
    id: '/maintenance',
    path: '/maintenance',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLeasingProcessRoute =
  AuthenticatedLeasingProcessRouteImport.update({
    id: '/leasing-process',
    path: '/leasing-process',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInvestorRoute = AuthenticatedInvestorRouteImport.update({
  id: '/investor',
  path: '/investor',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInspectionsRoute =
  AuthenticatedInspectionsRouteImport.update({
    id: '/inspections',
    path: '/inspections',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFinancialsRoute = AuthenticatedFinancialsRouteImport.update({
  id: '/financials',
  path: '/financials',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedComplianceRoute = AuthenticatedComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAiInsightsRoute = AuthenticatedAiInsightsRouteImport.update({
  id: '/ai-insights',
  path: '/ai-insights',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAccountingRoute = AuthenticatedAccountingRouteImport.update({
  id: '/accounting',
  path: '/accounting',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/(auth)/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const authOtpRoute = authOtpRouteImport.update({
  id: '/(auth)/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSuppliersIndexRoute =
  AuthenticatedSuppliersIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSuppliersRoute,
  } as any)
const AuthenticatedReportsIndexRoute =
  AuthenticatedReportsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedReportsRoute,
  } as any)
const AuthenticatedPropertiesIndexRoute =
  AuthenticatedPropertiesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPropertiesRoute,
  } as any)
const AuthenticatedLeasingProcessIndexRoute =
  AuthenticatedLeasingProcessIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedLeasingProcessRoute,
  } as any)
const AuthenticatedSuppliersReviewsRoute =
  AuthenticatedSuppliersReviewsRouteImport.update({
    id: '/reviews',
    path: '/reviews',
    getParentRoute: () => AuthenticatedSuppliersRoute,
  } as any)
const AuthenticatedSuppliersQuotesRoute =
  AuthenticatedSuppliersQuotesRouteImport.update({
    id: '/quotes',
    path: '/quotes',
    getParentRoute: () => AuthenticatedSuppliersRoute,
  } as any)
const AuthenticatedSuppliersAssignmentsRoute =
  AuthenticatedSuppliersAssignmentsRouteImport.update({
    id: '/assignments',
    path: '/assignments',
    getParentRoute: () => AuthenticatedSuppliersRoute,
  } as any)
const AuthenticatedReportsRentalPriceRoute =
  AuthenticatedReportsRentalPriceRouteImport.update({
    id: '/rental-price',
    path: '/rental-price',
    getParentRoute: () => AuthenticatedReportsRoute,
  } as any)
const AuthenticatedPropertiesPropertyIdRoute =
  AuthenticatedPropertiesPropertyIdRouteImport.update({
    id: '/$propertyId',
    path: '/$propertyId',
    getParentRoute: () => AuthenticatedPropertiesRoute,
  } as any)
const AuthenticatedMarketingOldOwnersRoute =
  AuthenticatedMarketingOldOwnersRouteImport.update({
    id: '/old-owners',
    path: '/old-owners',
    getParentRoute: () => AuthenticatedMarketingRoute,
  } as any)
const AuthenticatedMarketingLeadsRoute =
  AuthenticatedMarketingLeadsRouteImport.update({
    id: '/leads',
    path: '/leads',
    getParentRoute: () => AuthenticatedMarketingRoute,
  } as any)
const AuthenticatedLeasingProcessViewingRoute =
  AuthenticatedLeasingProcessViewingRouteImport.update({
    id: '/viewing',
    path: '/viewing',
    getParentRoute: () => AuthenticatedLeasingProcessRoute,
  } as any)
const AuthenticatedLeasingProcessListingRoute =
  AuthenticatedLeasingProcessListingRouteImport.update({
    id: '/listing',
    path: '/listing',
    getParentRoute: () => AuthenticatedLeasingProcessRoute,
  } as any)
const AuthenticatedLeasingProcessApplicationsRoute =
  AuthenticatedLeasingProcessApplicationsRouteImport.update({
    id: '/applications',
    path: '/applications',
    getParentRoute: () => AuthenticatedLeasingProcessRoute,
  } as any)
const AuthenticatedLeasingProcessAgreementsRoute =
  AuthenticatedLeasingProcessAgreementsRouteImport.update({
    id: '/agreements',
    path: '/agreements',
    getParentRoute: () => AuthenticatedLeasingProcessRoute,
  } as any)
const AuthenticatedAccountingAuditRoute =
  AuthenticatedAccountingAuditRouteImport.update({
    id: '/audit',
    path: '/audit',
    getParentRoute: () => AuthenticatedAccountingRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/accounting': typeof AuthenticatedAccountingRouteWithChildren
  '/ai-insights': typeof AuthenticatedAiInsightsRoute
  '/compliance': typeof AuthenticatedComplianceRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/financials': typeof AuthenticatedFinancialsRoute
  '/inspections': typeof AuthenticatedInspectionsRoute
  '/investor': typeof AuthenticatedInvestorRoute
  '/leasing-process': typeof AuthenticatedLeasingProcessRouteWithChildren
  '/maintenance': typeof AuthenticatedMaintenanceRoute
  '/marketing': typeof AuthenticatedMarketingRouteWithChildren
  '/owners': typeof AuthenticatedOwnersRoute
  '/properties': typeof AuthenticatedPropertiesRouteWithChildren
  '/reports': typeof AuthenticatedReportsRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRoute
  '/suppliers': typeof AuthenticatedSuppliersRouteWithChildren
  '/tenancies': typeof AuthenticatedTenanciesRoute
  '/tenants': typeof AuthenticatedTenantsRoute
  '/workbench': typeof AuthenticatedWorkbenchRoute
  '/': typeof AuthenticatedIndexRoute
  '/accounting/audit': typeof AuthenticatedAccountingAuditRoute
  '/leasing-process/agreements': typeof AuthenticatedLeasingProcessAgreementsRoute
  '/leasing-process/applications': typeof AuthenticatedLeasingProcessApplicationsRoute
  '/leasing-process/listing': typeof AuthenticatedLeasingProcessListingRoute
  '/leasing-process/viewing': typeof AuthenticatedLeasingProcessViewingRoute
  '/marketing/leads': typeof AuthenticatedMarketingLeadsRoute
  '/marketing/old-owners': typeof AuthenticatedMarketingOldOwnersRoute
  '/properties/$propertyId': typeof AuthenticatedPropertiesPropertyIdRoute
  '/reports/rental-price': typeof AuthenticatedReportsRentalPriceRoute
  '/suppliers/assignments': typeof AuthenticatedSuppliersAssignmentsRoute
  '/suppliers/quotes': typeof AuthenticatedSuppliersQuotesRoute
  '/suppliers/reviews': typeof AuthenticatedSuppliersReviewsRoute
  '/leasing-process/': typeof AuthenticatedLeasingProcessIndexRoute
  '/properties/': typeof AuthenticatedPropertiesIndexRoute
  '/reports/': typeof AuthenticatedReportsIndexRoute
  '/suppliers/': typeof AuthenticatedSuppliersIndexRoute
}
export interface FileRoutesByTo {
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/accounting': typeof AuthenticatedAccountingRouteWithChildren
  '/ai-insights': typeof AuthenticatedAiInsightsRoute
  '/compliance': typeof AuthenticatedComplianceRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/financials': typeof AuthenticatedFinancialsRoute
  '/inspections': typeof AuthenticatedInspectionsRoute
  '/investor': typeof AuthenticatedInvestorRoute
  '/maintenance': typeof AuthenticatedMaintenanceRoute
  '/marketing': typeof AuthenticatedMarketingRouteWithChildren
  '/owners': typeof AuthenticatedOwnersRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/tenancies': typeof AuthenticatedTenanciesRoute
  '/tenants': typeof AuthenticatedTenantsRoute
  '/workbench': typeof AuthenticatedWorkbenchRoute
  '/': typeof AuthenticatedIndexRoute
  '/accounting/audit': typeof AuthenticatedAccountingAuditRoute
  '/leasing-process/agreements': typeof AuthenticatedLeasingProcessAgreementsRoute
  '/leasing-process/applications': typeof AuthenticatedLeasingProcessApplicationsRoute
  '/leasing-process/listing': typeof AuthenticatedLeasingProcessListingRoute
  '/leasing-process/viewing': typeof AuthenticatedLeasingProcessViewingRoute
  '/marketing/leads': typeof AuthenticatedMarketingLeadsRoute
  '/marketing/old-owners': typeof AuthenticatedMarketingOldOwnersRoute
  '/properties/$propertyId': typeof AuthenticatedPropertiesPropertyIdRoute
  '/reports/rental-price': typeof AuthenticatedReportsRentalPriceRoute
  '/suppliers/assignments': typeof AuthenticatedSuppliersAssignmentsRoute
  '/suppliers/quotes': typeof AuthenticatedSuppliersQuotesRoute
  '/suppliers/reviews': typeof AuthenticatedSuppliersReviewsRoute
  '/leasing-process': typeof AuthenticatedLeasingProcessIndexRoute
  '/properties': typeof AuthenticatedPropertiesIndexRoute
  '/reports': typeof AuthenticatedReportsIndexRoute
  '/suppliers': typeof AuthenticatedSuppliersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/otp': typeof authOtpRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/_authenticated/accounting': typeof AuthenticatedAccountingRouteWithChildren
  '/_authenticated/ai-insights': typeof AuthenticatedAiInsightsRoute
  '/_authenticated/compliance': typeof AuthenticatedComplianceRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/financials': typeof AuthenticatedFinancialsRoute
  '/_authenticated/inspections': typeof AuthenticatedInspectionsRoute
  '/_authenticated/investor': typeof AuthenticatedInvestorRoute
  '/_authenticated/leasing-process': typeof AuthenticatedLeasingProcessRouteWithChildren
  '/_authenticated/maintenance': typeof AuthenticatedMaintenanceRoute
  '/_authenticated/marketing': typeof AuthenticatedMarketingRouteWithChildren
  '/_authenticated/owners': typeof AuthenticatedOwnersRoute
  '/_authenticated/properties': typeof AuthenticatedPropertiesRouteWithChildren
  '/_authenticated/reports': typeof AuthenticatedReportsRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/suppliers': typeof AuthenticatedSuppliersRouteWithChildren
  '/_authenticated/tenancies': typeof AuthenticatedTenanciesRoute
  '/_authenticated/tenants': typeof AuthenticatedTenantsRoute
  '/_authenticated/workbench': typeof AuthenticatedWorkbenchRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/accounting/audit': typeof AuthenticatedAccountingAuditRoute
  '/_authenticated/leasing-process/agreements': typeof AuthenticatedLeasingProcessAgreementsRoute
  '/_authenticated/leasing-process/applications': typeof AuthenticatedLeasingProcessApplicationsRoute
  '/_authenticated/leasing-process/listing': typeof AuthenticatedLeasingProcessListingRoute
  '/_authenticated/leasing-process/viewing': typeof AuthenticatedLeasingProcessViewingRoute
  '/_authenticated/marketing/leads': typeof AuthenticatedMarketingLeadsRoute
  '/_authenticated/marketing/old-owners': typeof AuthenticatedMarketingOldOwnersRoute
  '/_authenticated/properties/$propertyId': typeof AuthenticatedPropertiesPropertyIdRoute
  '/_authenticated/reports/rental-price': typeof AuthenticatedReportsRentalPriceRoute
  '/_authenticated/suppliers/assignments': typeof AuthenticatedSuppliersAssignmentsRoute
  '/_authenticated/suppliers/quotes': typeof AuthenticatedSuppliersQuotesRoute
  '/_authenticated/suppliers/reviews': typeof AuthenticatedSuppliersReviewsRoute
  '/_authenticated/leasing-process/': typeof AuthenticatedLeasingProcessIndexRoute
  '/_authenticated/properties/': typeof AuthenticatedPropertiesIndexRoute
  '/_authenticated/reports/': typeof AuthenticatedReportsIndexRoute
  '/_authenticated/suppliers/': typeof AuthenticatedSuppliersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/accounting'
    | '/ai-insights'
    | '/compliance'
    | '/dashboard'
    | '/financials'
    | '/inspections'
    | '/investor'
    | '/leasing-process'
    | '/maintenance'
    | '/marketing'
    | '/owners'
    | '/properties'
    | '/reports'
    | '/settings'
    | '/suppliers'
    | '/tenancies'
    | '/tenants'
    | '/workbench'
    | '/'
    | '/accounting/audit'
    | '/leasing-process/agreements'
    | '/leasing-process/applications'
    | '/leasing-process/listing'
    | '/leasing-process/viewing'
    | '/marketing/leads'
    | '/marketing/old-owners'
    | '/properties/$propertyId'
    | '/reports/rental-price'
    | '/suppliers/assignments'
    | '/suppliers/quotes'
    | '/suppliers/reviews'
    | '/leasing-process/'
    | '/properties/'
    | '/reports/'
    | '/suppliers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/accounting'
    | '/ai-insights'
    | '/compliance'
    | '/dashboard'
    | '/financials'
    | '/inspections'
    | '/investor'
    | '/maintenance'
    | '/marketing'
    | '/owners'
    | '/settings'
    | '/tenancies'
    | '/tenants'
    | '/workbench'
    | '/'
    | '/accounting/audit'
    | '/leasing-process/agreements'
    | '/leasing-process/applications'
    | '/leasing-process/listing'
    | '/leasing-process/viewing'
    | '/marketing/leads'
    | '/marketing/old-owners'
    | '/properties/$propertyId'
    | '/reports/rental-price'
    | '/suppliers/assignments'
    | '/suppliers/quotes'
    | '/suppliers/reviews'
    | '/leasing-process'
    | '/properties'
    | '/reports'
    | '/suppliers'
  id:
    | '__root__'
    | '/_authenticated'
    | '/(auth)/forgot-password'
    | '/(auth)/otp'
    | '/(auth)/sign-in'
    | '/(auth)/sign-up'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_authenticated/accounting'
    | '/_authenticated/ai-insights'
    | '/_authenticated/compliance'
    | '/_authenticated/dashboard'
    | '/_authenticated/financials'
    | '/_authenticated/inspections'
    | '/_authenticated/investor'
    | '/_authenticated/leasing-process'
    | '/_authenticated/maintenance'
    | '/_authenticated/marketing'
    | '/_authenticated/owners'
    | '/_authenticated/properties'
    | '/_authenticated/reports'
    | '/_authenticated/settings'
    | '/_authenticated/suppliers'
    | '/_authenticated/tenancies'
    | '/_authenticated/tenants'
    | '/_authenticated/workbench'
    | '/_authenticated/'
    | '/_authenticated/accounting/audit'
    | '/_authenticated/leasing-process/agreements'
    | '/_authenticated/leasing-process/applications'
    | '/_authenticated/leasing-process/listing'
    | '/_authenticated/leasing-process/viewing'
    | '/_authenticated/marketing/leads'
    | '/_authenticated/marketing/old-owners'
    | '/_authenticated/properties/$propertyId'
    | '/_authenticated/reports/rental-price'
    | '/_authenticated/suppliers/assignments'
    | '/_authenticated/suppliers/quotes'
    | '/_authenticated/suppliers/reviews'
    | '/_authenticated/leasing-process/'
    | '/_authenticated/properties/'
    | '/_authenticated/reports/'
    | '/_authenticated/suppliers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authOtpRoute: typeof authOtpRoute
  authSignInRoute: typeof authSignInRoute
  authSignUpRoute: typeof authSignUpRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/workbench': {
      id: '/_authenticated/workbench'
      path: '/workbench'
      fullPath: '/workbench'
      preLoaderRoute: typeof AuthenticatedWorkbenchRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tenants': {
      id: '/_authenticated/tenants'
      path: '/tenants'
      fullPath: '/tenants'
      preLoaderRoute: typeof AuthenticatedTenantsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tenancies': {
      id: '/_authenticated/tenancies'
      path: '/tenancies'
      fullPath: '/tenancies'
      preLoaderRoute: typeof AuthenticatedTenanciesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/suppliers': {
      id: '/_authenticated/suppliers'
      path: '/suppliers'
      fullPath: '/suppliers'
      preLoaderRoute: typeof AuthenticatedSuppliersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/properties': {
      id: '/_authenticated/properties'
      path: '/properties'
      fullPath: '/properties'
      preLoaderRoute: typeof AuthenticatedPropertiesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/owners': {
      id: '/_authenticated/owners'
      path: '/owners'
      fullPath: '/owners'
      preLoaderRoute: typeof AuthenticatedOwnersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/marketing': {
      id: '/_authenticated/marketing'
      path: '/marketing'
      fullPath: '/marketing'
      preLoaderRoute: typeof AuthenticatedMarketingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/maintenance': {
      id: '/_authenticated/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof AuthenticatedMaintenanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leasing-process': {
      id: '/_authenticated/leasing-process'
      path: '/leasing-process'
      fullPath: '/leasing-process'
      preLoaderRoute: typeof AuthenticatedLeasingProcessRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/investor': {
      id: '/_authenticated/investor'
      path: '/investor'
      fullPath: '/investor'
      preLoaderRoute: typeof AuthenticatedInvestorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inspections': {
      id: '/_authenticated/inspections'
      path: '/inspections'
      fullPath: '/inspections'
      preLoaderRoute: typeof AuthenticatedInspectionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/financials': {
      id: '/_authenticated/financials'
      path: '/financials'
      fullPath: '/financials'
      preLoaderRoute: typeof AuthenticatedFinancialsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/compliance': {
      id: '/_authenticated/compliance'
      path: '/compliance'
      fullPath: '/compliance'
      preLoaderRoute: typeof AuthenticatedComplianceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ai-insights': {
      id: '/_authenticated/ai-insights'
      path: '/ai-insights'
      fullPath: '/ai-insights'
      preLoaderRoute: typeof AuthenticatedAiInsightsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/accounting': {
      id: '/_authenticated/accounting'
      path: '/accounting'
      fullPath: '/accounting'
      preLoaderRoute: typeof AuthenticatedAccountingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/otp': {
      id: '/(auth)/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof authOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/suppliers/': {
      id: '/_authenticated/suppliers/'
      path: '/'
      fullPath: '/suppliers/'
      preLoaderRoute: typeof AuthenticatedSuppliersIndexRouteImport
      parentRoute: typeof AuthenticatedSuppliersRoute
    }
    '/_authenticated/reports/': {
      id: '/_authenticated/reports/'
      path: '/'
      fullPath: '/reports/'
      preLoaderRoute: typeof AuthenticatedReportsIndexRouteImport
      parentRoute: typeof AuthenticatedReportsRoute
    }
    '/_authenticated/properties/': {
      id: '/_authenticated/properties/'
      path: '/'
      fullPath: '/properties/'
      preLoaderRoute: typeof AuthenticatedPropertiesIndexRouteImport
      parentRoute: typeof AuthenticatedPropertiesRoute
    }
    '/_authenticated/leasing-process/': {
      id: '/_authenticated/leasing-process/'
      path: '/'
      fullPath: '/leasing-process/'
      preLoaderRoute: typeof AuthenticatedLeasingProcessIndexRouteImport
      parentRoute: typeof AuthenticatedLeasingProcessRoute
    }
    '/_authenticated/suppliers/reviews': {
      id: '/_authenticated/suppliers/reviews'
      path: '/reviews'
      fullPath: '/suppliers/reviews'
      preLoaderRoute: typeof AuthenticatedSuppliersReviewsRouteImport
      parentRoute: typeof AuthenticatedSuppliersRoute
    }
    '/_authenticated/suppliers/quotes': {
      id: '/_authenticated/suppliers/quotes'
      path: '/quotes'
      fullPath: '/suppliers/quotes'
      preLoaderRoute: typeof AuthenticatedSuppliersQuotesRouteImport
      parentRoute: typeof AuthenticatedSuppliersRoute
    }
    '/_authenticated/suppliers/assignments': {
      id: '/_authenticated/suppliers/assignments'
      path: '/assignments'
      fullPath: '/suppliers/assignments'
      preLoaderRoute: typeof AuthenticatedSuppliersAssignmentsRouteImport
      parentRoute: typeof AuthenticatedSuppliersRoute
    }
    '/_authenticated/reports/rental-price': {
      id: '/_authenticated/reports/rental-price'
      path: '/rental-price'
      fullPath: '/reports/rental-price'
      preLoaderRoute: typeof AuthenticatedReportsRentalPriceRouteImport
      parentRoute: typeof AuthenticatedReportsRoute
    }
    '/_authenticated/properties/$propertyId': {
      id: '/_authenticated/properties/$propertyId'
      path: '/$propertyId'
      fullPath: '/properties/$propertyId'
      preLoaderRoute: typeof AuthenticatedPropertiesPropertyIdRouteImport
      parentRoute: typeof AuthenticatedPropertiesRoute
    }
    '/_authenticated/marketing/old-owners': {
      id: '/_authenticated/marketing/old-owners'
      path: '/old-owners'
      fullPath: '/marketing/old-owners'
      preLoaderRoute: typeof AuthenticatedMarketingOldOwnersRouteImport
      parentRoute: typeof AuthenticatedMarketingRoute
    }
    '/_authenticated/marketing/leads': {
      id: '/_authenticated/marketing/leads'
      path: '/leads'
      fullPath: '/marketing/leads'
      preLoaderRoute: typeof AuthenticatedMarketingLeadsRouteImport
      parentRoute: typeof AuthenticatedMarketingRoute
    }
    '/_authenticated/leasing-process/viewing': {
      id: '/_authenticated/leasing-process/viewing'
      path: '/viewing'
      fullPath: '/leasing-process/viewing'
      preLoaderRoute: typeof AuthenticatedLeasingProcessViewingRouteImport
      parentRoute: typeof AuthenticatedLeasingProcessRoute
    }
    '/_authenticated/leasing-process/listing': {
      id: '/_authenticated/leasing-process/listing'
      path: '/listing'
      fullPath: '/leasing-process/listing'
      preLoaderRoute: typeof AuthenticatedLeasingProcessListingRouteImport
      parentRoute: typeof AuthenticatedLeasingProcessRoute
    }
    '/_authenticated/leasing-process/applications': {
      id: '/_authenticated/leasing-process/applications'
      path: '/applications'
      fullPath: '/leasing-process/applications'
      preLoaderRoute: typeof AuthenticatedLeasingProcessApplicationsRouteImport
      parentRoute: typeof AuthenticatedLeasingProcessRoute
    }
    '/_authenticated/leasing-process/agreements': {
      id: '/_authenticated/leasing-process/agreements'
      path: '/agreements'
      fullPath: '/leasing-process/agreements'
      preLoaderRoute: typeof AuthenticatedLeasingProcessAgreementsRouteImport
      parentRoute: typeof AuthenticatedLeasingProcessRoute
    }
    '/_authenticated/accounting/audit': {
      id: '/_authenticated/accounting/audit'
      path: '/audit'
      fullPath: '/accounting/audit'
      preLoaderRoute: typeof AuthenticatedAccountingAuditRouteImport
      parentRoute: typeof AuthenticatedAccountingRoute
    }
  }
}

interface AuthenticatedAccountingRouteChildren {
  AuthenticatedAccountingAuditRoute: typeof AuthenticatedAccountingAuditRoute
}

const AuthenticatedAccountingRouteChildren: AuthenticatedAccountingRouteChildren =
  {
    AuthenticatedAccountingAuditRoute: AuthenticatedAccountingAuditRoute,
  }

const AuthenticatedAccountingRouteWithChildren =
  AuthenticatedAccountingRoute._addFileChildren(
    AuthenticatedAccountingRouteChildren,
  )

interface AuthenticatedLeasingProcessRouteChildren {
  AuthenticatedLeasingProcessAgreementsRoute: typeof AuthenticatedLeasingProcessAgreementsRoute
  AuthenticatedLeasingProcessApplicationsRoute: typeof AuthenticatedLeasingProcessApplicationsRoute
  AuthenticatedLeasingProcessListingRoute: typeof AuthenticatedLeasingProcessListingRoute
  AuthenticatedLeasingProcessViewingRoute: typeof AuthenticatedLeasingProcessViewingRoute
  AuthenticatedLeasingProcessIndexRoute: typeof AuthenticatedLeasingProcessIndexRoute
}

const AuthenticatedLeasingProcessRouteChildren: AuthenticatedLeasingProcessRouteChildren =
  {
    AuthenticatedLeasingProcessAgreementsRoute:
      AuthenticatedLeasingProcessAgreementsRoute,
    AuthenticatedLeasingProcessApplicationsRoute:
      AuthenticatedLeasingProcessApplicationsRoute,
    AuthenticatedLeasingProcessListingRoute:
      AuthenticatedLeasingProcessListingRoute,
    AuthenticatedLeasingProcessViewingRoute:
      AuthenticatedLeasingProcessViewingRoute,
    AuthenticatedLeasingProcessIndexRoute:
      AuthenticatedLeasingProcessIndexRoute,
  }

const AuthenticatedLeasingProcessRouteWithChildren =
  AuthenticatedLeasingProcessRoute._addFileChildren(
    AuthenticatedLeasingProcessRouteChildren,
  )

interface AuthenticatedMarketingRouteChildren {
  AuthenticatedMarketingLeadsRoute: typeof AuthenticatedMarketingLeadsRoute
  AuthenticatedMarketingOldOwnersRoute: typeof AuthenticatedMarketingOldOwnersRoute
}

const AuthenticatedMarketingRouteChildren: AuthenticatedMarketingRouteChildren =
  {
    AuthenticatedMarketingLeadsRoute: AuthenticatedMarketingLeadsRoute,
    AuthenticatedMarketingOldOwnersRoute: AuthenticatedMarketingOldOwnersRoute,
  }

const AuthenticatedMarketingRouteWithChildren =
  AuthenticatedMarketingRoute._addFileChildren(
    AuthenticatedMarketingRouteChildren,
  )

interface AuthenticatedPropertiesRouteChildren {
  AuthenticatedPropertiesPropertyIdRoute: typeof AuthenticatedPropertiesPropertyIdRoute
  AuthenticatedPropertiesIndexRoute: typeof AuthenticatedPropertiesIndexRoute
}

const AuthenticatedPropertiesRouteChildren: AuthenticatedPropertiesRouteChildren =
  {
    AuthenticatedPropertiesPropertyIdRoute:
      AuthenticatedPropertiesPropertyIdRoute,
    AuthenticatedPropertiesIndexRoute: AuthenticatedPropertiesIndexRoute,
  }

const AuthenticatedPropertiesRouteWithChildren =
  AuthenticatedPropertiesRoute._addFileChildren(
    AuthenticatedPropertiesRouteChildren,
  )

interface AuthenticatedReportsRouteChildren {
  AuthenticatedReportsRentalPriceRoute: typeof AuthenticatedReportsRentalPriceRoute
  AuthenticatedReportsIndexRoute: typeof AuthenticatedReportsIndexRoute
}

const AuthenticatedReportsRouteChildren: AuthenticatedReportsRouteChildren = {
  AuthenticatedReportsRentalPriceRoute: AuthenticatedReportsRentalPriceRoute,
  AuthenticatedReportsIndexRoute: AuthenticatedReportsIndexRoute,
}

const AuthenticatedReportsRouteWithChildren =
  AuthenticatedReportsRoute._addFileChildren(AuthenticatedReportsRouteChildren)

interface AuthenticatedSuppliersRouteChildren {
  AuthenticatedSuppliersAssignmentsRoute: typeof AuthenticatedSuppliersAssignmentsRoute
  AuthenticatedSuppliersQuotesRoute: typeof AuthenticatedSuppliersQuotesRoute
  AuthenticatedSuppliersReviewsRoute: typeof AuthenticatedSuppliersReviewsRoute
  AuthenticatedSuppliersIndexRoute: typeof AuthenticatedSuppliersIndexRoute
}

const AuthenticatedSuppliersRouteChildren: AuthenticatedSuppliersRouteChildren =
  {
    AuthenticatedSuppliersAssignmentsRoute:
      AuthenticatedSuppliersAssignmentsRoute,
    AuthenticatedSuppliersQuotesRoute: AuthenticatedSuppliersQuotesRoute,
    AuthenticatedSuppliersReviewsRoute: AuthenticatedSuppliersReviewsRoute,
    AuthenticatedSuppliersIndexRoute: AuthenticatedSuppliersIndexRoute,
  }

const AuthenticatedSuppliersRouteWithChildren =
  AuthenticatedSuppliersRoute._addFileChildren(
    AuthenticatedSuppliersRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccountingRoute: typeof AuthenticatedAccountingRouteWithChildren
  AuthenticatedAiInsightsRoute: typeof AuthenticatedAiInsightsRoute
  AuthenticatedComplianceRoute: typeof AuthenticatedComplianceRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFinancialsRoute: typeof AuthenticatedFinancialsRoute
  AuthenticatedInspectionsRoute: typeof AuthenticatedInspectionsRoute
  AuthenticatedInvestorRoute: typeof AuthenticatedInvestorRoute
  AuthenticatedLeasingProcessRoute: typeof AuthenticatedLeasingProcessRouteWithChildren
  AuthenticatedMaintenanceRoute: typeof AuthenticatedMaintenanceRoute
  AuthenticatedMarketingRoute: typeof AuthenticatedMarketingRouteWithChildren
  AuthenticatedOwnersRoute: typeof AuthenticatedOwnersRoute
  AuthenticatedPropertiesRoute: typeof AuthenticatedPropertiesRouteWithChildren
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRouteWithChildren
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSuppliersRoute: typeof AuthenticatedSuppliersRouteWithChildren
  AuthenticatedTenanciesRoute: typeof AuthenticatedTenanciesRoute
  AuthenticatedTenantsRoute: typeof AuthenticatedTenantsRoute
  AuthenticatedWorkbenchRoute: typeof AuthenticatedWorkbenchRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccountingRoute: AuthenticatedAccountingRouteWithChildren,
  AuthenticatedAiInsightsRoute: AuthenticatedAiInsightsRoute,
  AuthenticatedComplianceRoute: AuthenticatedComplianceRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFinancialsRoute: AuthenticatedFinancialsRoute,
  AuthenticatedInspectionsRoute: AuthenticatedInspectionsRoute,
  AuthenticatedInvestorRoute: AuthenticatedInvestorRoute,
  AuthenticatedLeasingProcessRoute:
    AuthenticatedLeasingProcessRouteWithChildren,
  AuthenticatedMaintenanceRoute: AuthenticatedMaintenanceRoute,
  AuthenticatedMarketingRoute: AuthenticatedMarketingRouteWithChildren,
  AuthenticatedOwnersRoute: AuthenticatedOwnersRoute,
  AuthenticatedPropertiesRoute: AuthenticatedPropertiesRouteWithChildren,
  AuthenticatedReportsRoute: AuthenticatedReportsRouteWithChildren,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSuppliersRoute: AuthenticatedSuppliersRouteWithChildren,
  AuthenticatedTenanciesRoute: AuthenticatedTenanciesRoute,
  AuthenticatedTenantsRoute: AuthenticatedTenantsRoute,
  AuthenticatedWorkbenchRoute: AuthenticatedWorkbenchRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authOtpRoute: authOtpRoute,
  authSignInRoute: authSignInRoute,
  authSignUpRoute: authSignUpRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
